// <auto-generated />
using System;
using AssetManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("AssignedToUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assets_assignment_consistency", "(\r\n                (\"Status\" = 'InUse' AND \"AssignedToUserId\" IS NOT NULL AND \"AssignedAtUtc\" IS NOT NULL)\r\n                OR\r\n                (\"Status\" <> 'InUse' AND \"AssignedToUserId\" IS NULL AND \"AssignedAtUtc\" IS NULL)\r\n                )");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssetTypeId = 1L,
                            Name = "MacBook Pro M3",
                            SerialNumber = "SN123",
                            Status = "Available",
                            Value = 15000.00m
                        },
                        new
                        {
                            Id = 2L,
                            AssetTypeId = 2L,
                            Name = "Acer Aspire 5",
                            SerialNumber = "SN456",
                            Status = "Available",
                            Value = 3500.00m
                        },
                        new
                        {
                            Id = 3L,
                            AssetTypeId = 2L,
                            Name = "Dell UltraSharp 27",
                            SerialNumber = "SN789",
                            Status = "Maintenance",
                            Value = 3500.00m
                        },
                        new
                        {
                            Id = 4L,
                            AssetTypeId = 3L,
                            Name = "Dell Tower Plus Intel Core Ultra 5",
                            SerialNumber = "SN987",
                            Status = "Available",
                            Value = 9999.99m
                        },
                        new
                        {
                            Id = 5L,
                            AssetTypeId = 4L,
                            Name = "Mouse Logitech",
                            SerialNumber = "SN654",
                            Status = "Available",
                            Value = 30.00m
                        },
                        new
                        {
                            Id = 6L,
                            AssetTypeId = 4L,
                            Name = "Multifuncional HP",
                            SerialNumber = "SN321",
                            Status = "Maintenance",
                            Value = 1500.00m
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AssetAllocationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.HasIndex("AssetId", "AtUtc");

                    b.ToTable("asset_allocation_logs", (string)null);
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AssetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("asset_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "NOTEBOOK"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "MONITOR"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "DESKTOP"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "PERIFÉRICOS"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "ana@mail.com",
                            Name = "Ana"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "luis@mail.com",
                            Name = "Luís"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "jose@mail.com",
                            Name = "José"
                        });
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.AssetType", "Type")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedAssets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AssetAllocationLog", b =>
                {
                    b.HasOne("AssetManagement.Domain.Entities.Asset", "Asset")
                        .WithMany("AllocationLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagement.Domain.Entities.User", "User")
                        .WithMany("AllocationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AllocationLogs");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("AssetManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("AllocationLogs");

                    b.Navigation("AssignedAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
